todo/urls.py
from django.urls import path

from .views import (
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskUpdateDoneView,
)

app_name = "todo"

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "<int:pk>/update-done/",
        TaskUpdateDoneView.as_view(),
        name="task-update-done"
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

todo_list/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from todo_list import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField()
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "created"]

    def __str__(self):
        return self.content

todo/forms.py
from django import forms

from .models import Tag, Task


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Task
        fields = "__all__"

todo/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views import generic

from .forms import TaskForm
from .models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")


class TaskCreateView(generic.CreateView):
    form_class = TaskForm
    template_name = "todo/task_form.html"
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "todo/task_form.html"
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateDoneView(generic.RedirectView):
    def post(self, request, *args, **kwargs):
        task = Task.objects.get(id=kwargs["pk"])
        task.is_done = not task.is_done
        task.save()
        return HttpResponseRedirect(reverse("todo:task-list"))


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock sidebar %}
    </div>

    <div class="col-sm-10">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
</div>
</body>
</html>

templates/includes/confirm_delete_form.html
<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes" class="btn btn-danger">
  <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-dark">Cancel</a>
</form>

templates/includes/form.html
{% load crispy_forms_filters %}
<form action="" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Submit">
</form>

templates/includes/sidebar.html
<div class="sidebar" style="max-width: 150px">
  <ul class="nav flex-column">
    <li class="nav-item border">
      <a href="{% url 'todo:task-list' %}" class="nav-link active">
        Home
      </a>
    </li>
    <li class="nav-item border">
      <a href="{% url 'todo:tag-list' %}" class="nav-link active">
        Tags
      </a>
    </li>
  </ul>
</div>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete Tag{% endblock %}

{% block content %}
  <h1>Are you sure you want to delete this tag?</h1>
  <p>The tasks with this tag <strong>will not</strong> be deleted.</p>
  {% include "includes/confirm_delete_form.html" %}
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}

{% block title %}Tag{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update the ,Add a new " }}tag</h1>
  {% include "includes/form.html" %}
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block title %}Tags{% endblock %}

{% block content %}
  <h1>
    Tags
    <a href="{% url 'todo:tag-create' %}" class="btn btn-primary float-right">
      Add
    </a>
  </h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for tag in tag_list %}
      	<tr>
          <td>{{ tag.name }}</td>
          <td>
            <a href="{% url 'todo:tag-update' tag.id %}" class="btn btn-secondary">
              Update
            </a>
          </td>
          <td>
            <a href="{% url 'todo:tag-delete' tag.id %}" class="btn btn-secondary">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}

    </tbody>
  </table>
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete Task{% endblock %}

{% block content %}
  <h1>Are you sure you want to delete this task?</h1>
  {% include "includes/confirm_delete_form.html" %}
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}

{% block title %}Task{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update the ,Add a new " }}task</h1>
  {% include "includes/form.html" %}
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block title %}Todo List{% endblock %}

{% block content %}
  <h1 class="pb-3">
    TODO list
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary float-right">
        Add task
      </a>
  </h1>

  {% for task in task_list %}
    <h5>
      {{ task.content }}
      {% if task.is_done %}
        <span class="text-success">Done</span>
        <form action="{% url 'todo:task-update-done' task.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Undo" class="btn btn-secondary float-right">
        </form>
      {% else %}
        <span class="text-danger">Not done</span>
        <form action="{% url 'todo:task-update-done' task.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Complete" class="btn btn-success float-right">
        </form>
      {% endif %}
    </h5>
    <p>
      Created: {{ task.created }} <span style="color: maroon">Deadline: {{ task.deadline }}</span>
    </p>
    <p>
      <span class="text-muted">
        Tags: {% for tag in task.tags.all %}{{ tag.name }}{% endfor %}
      </span>
      <a href="{% url 'todo:task-update' task.id %}">Update</a>
      <a href="{% url 'todo:task-delete' task.id %}">Delete</a>
    </p>
    <hr>
  {% endfor %}
{%  endblock %}